version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - funlen
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gocyclo
    - godox
    - mnd
    - goprintffuncname
    - gosec
    - govet
    - intrange
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    lll:
      line-length: 120
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
    goconst:
      min-len: 2
      min-occurrences: 2
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
      require-specific: true
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
    unparam:
      check-exported: false
    revive:
      rules:
        - name: indent-error-flow
        - name: unexported-return
          disabled: true
        - name: unused-parameter
        - name: unused-receiver
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - funlen
          - dupl
        path: _test\.go
      - linters:
          - gosec
        path: _test\.go
        text: 'G404: Use of weak random number generator'
      - path: (.+)\.go$
        text: G104
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
    goimports:
      local-prefixes:
        - github.com/94peter/vulpes
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$